### ISSUE TITLE
Header does not stay in place for wide charts

### ISSUE THREAD

**Issue by domoritz** [RandomFractals/vscode-vega-viewer#51] opened 2019-11-12 01:24 UTC
The header moves when I side-scroll a large chart. I think the header should stay in place. 

<img width="702" alt="Screen Shot 2019-11-11 at 17 23 58" src="https://user-images.githubusercontent.com/589034/68633804-1580c980-04a8-11ea-8ed6-1fa3d5abb670.png">

**Comment by RandomFractals** [comment] 2019-11-12 01:45
might be another minor Mac UI issue. what vscode v. & Mac OS are you on?

**Comment by domoritz** [comment] 2019-11-12 01:46
Version: 1.40.0
Commit: 86405ea23e3937316009fc27c9361deee66ffbf5
Date: 2019-11-06T17:09:34.601Z
Electron: 6.1.2
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 19.0.0

**Comment by RandomFractals** [comment] 2019-11-12 01:59
thank you for that info.

 I'll look into it, but I just want to be clear those minor dropdown UX issues you have been complaining about are lower priority for me at this point.

**Comment by domoritz** [comment] 2019-11-12 02:27
I'm sorry if I was complaining. I am trying to make suggestions that improve the user experience so that I can comfortably recommend this extension.

**Comment by RandomFractals** [comment] 2019-11-12 02:33
well, I think with close to 1K installs you can comfortably recommend it. It's more than devs on your Slack & I wish you promoted it more since most devs do use vscode today & local data snapshots for exploratory data analysis that your online Vega Editor doesn't really provide for quick charts prototypes & commits ...

& all those dropdown issues you logged today are minor UX issues. I think most devs would agree with me on that.

**Comment by RandomFractals** [comment] 2019-12-12 17:05
@domoritz I am not sure how you arrived at that vega viewer pic & I can't reproduce it.

Here is a snapshot of what I get on my 34 inch wide screen on win :)

I am going to close this issue as invalid and will not fix, unless I see more confirmed reports for your case from Mac users.

![vscode-vega-viewer-wide-screen](https://user-images.githubusercontent.com/656833/70733161-6108dc00-1ccf-11ea-8eda-95124d7c32ba.png)

**Closed as completed by RandomFractals** 2019-12-12 17:05 UTC
Labels: invalid, wontfix, UX, minor

**Comment by RandomFractals** [comment] 2019-12-12 17:07
@domoritz perhaps it's the custom beige UI theme you are using.

Please try it with the default light || dark theme in vscode.
