### ISSUE TITLE
change data preview command default to vscode.open

### ISSUE THREAD

**Issue by domoritz** [RandomFractals/vscode-vega-viewer#52] opened 2019-11-12 01:26 UTC
I am trying to use the data viewer but nothing happens when I select a dataset in the dropdown. 

Maybe I'm also misunderstanding this feature.

**Comment by RandomFractals** [comment] 2019-11-12 01:29
did you try to toggle it? :) 

see : https://github.com/RandomFractals/vscode-vega-viewer/releases/tag/v6.10.0

&& https://github.com/RandomFractals/vscode-vega-viewer/releases/tag/v6.9.0

Please share a screen pic & vega json you are trying it with.

Otherwise, I'll close this as invalid since it does not sound right to me per VV v. updates above :)

**Comment by RandomFractals** [comment] 2019-11-12 01:29
Please share a screen pic & a sample of vega json you are trying it with.

**Comment by domoritz** [comment] 2019-11-12 01:53
I don't have the data viewer installed. It does work if I change the setting but the default action does not work. 

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v4.json",
  "description": "An interactive visualization of connections among major U.S. airports in 2008. Based on a U.S. airports example by Mike Bostock.",
  "layer": [
    {
      "mark": {
        "type": "geoshape",
        "fill": "#ddd",
        "stroke": "#fff",
        "strokeWidth": 1
      },
      "data": {
        "url": "data/us-10m.json",
        "format": {"type": "topojson", "feature": "states"}
      }
    },
    {
      "mark": {"type": "rule", "color": "#000", "opacity": 0.35},
      "data": {"url": "data/flights-airport.csv"},
      "transform": [
        {"filter": {"selection": "single"}},
        {
          "lookup": "origin",
          "from": {
            "data": {"url": "data/airports.csv"},
            "key": "iata",
            "fields": ["latitude", "longitude"]
          }
        },
        {
          "lookup": "destination",
          "from": {
            "data": {"url": "data/airports.csv"},
            "key": "iata",
            "fields": ["latitude", "longitude"]
          },
          "as": ["lat2", "lon2"]
        }
      ],
      "encoding": {
        "latitude": {"field": "latitude", "type": "quantitative"},
        "longitude": {"field": "longitude", "type": "quantitative"},
        "latitude2": {"field": "lat2"},
        "longitude2": {"field": "lon2"}
      }
    },
    {
      "mark": {"type": "circle"},
      "data": {"url": "data/flights-airport.csv"},
      "transform": [
        {"aggregate": [{"op": "count", "as": "routes"}], "groupby": ["origin"]},
        {
          "lookup": "origin",
          "from": {
            "data": {"url": "data/airports.csv"},
            "key": "iata",
            "fields": ["state", "latitude", "longitude"]
          }
        },
        {"filter": "datum.state !== 'PR' && datum.state !== 'VI'"}
      ],
      "selection": {
        "single": {
          "type": "single",
          "on": "mouseover",
          "nearest": true,
          "fields": ["origin"],
          "empty": "none"
        }
      },
      "encoding": {
        "latitude": {"field": "latitude", "type": "quantitative"},
        "longitude": {"field": "longitude", "type": "quantitative"},
        "size": {
          "field": "routes",
          "type": "quantitative",
          "scale": {"range": [0, 1000]},
          "legend": null
        },
        "order": {
          "field": "routes",
          "type": "quantitative",
          "sort": "descending"
        }
      }
    }
  ],
  "projection": {"type": "albersUsa"},
  "width": 900,
  "height": 500,
  "config": {"view": {"stroke": null}}
}
```

<img width="1792" alt="Screen Shot 2019-11-11 at 17 53 23" src="https://user-images.githubusercontent.com/589034/68635040-2a5f5c00-04ac-11ea-98fc-4bd44db599ad.png">

**Comment by RandomFractals** [comment] 2019-11-12 02:04
well, then ... perhaps you should read the docs & see default settings? 

closing this as invalid.

**Comment by domoritz** [comment] 2019-11-12 02:26
I still believe this is a bug. The default should be just opening the file if the data viewer is not installed, don't you think?

**Comment by RandomFractals** [comment] 2019-11-12 02:27
perhaps, but that's not how I set it for now per my release notes ☝️

**Comment by domoritz** [comment] 2019-11-12 02:31
Okay, then I guess we have different priorities (which I'm cool with).

**Comment by RandomFractals** [comment] 2019-11-12 02:40
yeah, we play diff. data angles across the board ;) ...

**Comment by RandomFractals** [comment] 2019-11-13 11:31
@domoritz just an fyi: I added Settings section to docs that details how to change vega viewer data preview command setting. I had it in release notes but forgot to add it to docs.

So, this should be cleared up now :) https://github.com/RandomFractals/vscode-vega-viewer#settings

**Comment by domoritz** [comment] 2019-11-13 18:43
Thanks. Do you think that every user will read the docs first before using the extension? Or would it make sense to at least add a warning?

**Comment by RandomFractals** [comment] 2019-11-17 10:47
ok. I am gonna reopen this issue and push new update for this feature in the next v. with the following changes:

- default vega viewer data preview command to `vscode.open` for raw CSV & JSON data files preview
- check if `data.preview` ext. config is selected for that command and Data Preview ext. is installed for devs that would rather use data grid view for those data files, instead of raw data source code view

would that make it for a better UX of this feature?

& @domoritz thank you for your input on this migration of data preview implementation.

**Comment by RandomFractals** [comment] 2019-12-11 16:43
@domoritz quick 411 re. this change:

using vscode.open for data preview of remote data sources (http(s)) will actually go through vscode, but will try to open those data files in browser, might prompt to allow vscode to open it in browser and add that data source domain to the whitelist of sites vscode can open without prompts.

For the local data sources, it will open those data files in vscode for edits, etc.

You cool with that for now?

**Comment by domoritz** [comment] 2019-12-12 00:51
Sounds great.

**Comment by RandomFractals** [comment] 2019-12-12 17:01
closing this for now. I confirmed that even if you select to preview vega data with data preview and don't have that extension installed || enabled, vscode will just try to open referenced CVS & JSON data files raw for edits || in browser, depending on your data url in vega specs :)

**Closed as completed by RandomFractals** 2019-12-12 17:01 UTC
Labels: enhancement, UX
